runtime: nodejs
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.7
  disk_size_gb: 10
# [START configuration]
endpoints_api_service:
# The following values are to be replaced by information from the output of
# 'gcloud endpoints services deploy openapi-appengine.yaml' command.
   name: mygamecollectorexkapp.appspot.com
#rollout_strategy: managed
# Copyright 2015-2016, Google,
   config_id: 2019-09-17r0 # este config_id se cambia de acuerdo a la fecha actual
# [END configuration]

